# Generated by Django 4.2.3 on 2023-07-15 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_group_options_alter_group_owner_usercontacts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercontacts",
            old_name="members",
            new_name="contacts",
        ),
    ]
