# Generated by Django 4.2.3 on 2023-07-15 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_rename_members_usercontacts_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontacts",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
