# Generated by Django 4.2.3 on 2023-07-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_usercontacts_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("group", "Group")],
                default="group",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="UserContacts",
        ),
    ]
