# Generated by Django 4.2.3 on 2023-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_group_type_delete_usercontacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_pic",
            field=models.FileField(
                blank=True,
                default="group_pic/default_whatsapp_group_pic.jpg",
                max_length=355,
                null=True,
                upload_to="group_pic/",
            ),
        ),
    ]
