# Generated by Django 4.2.3 on 2023-07-21 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0007_alter_group_group_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="online",
            field=models.ManyToManyField(
                related_name="online", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
