# Generated by Django 4.2.3 on 2023-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_group_online"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["created_at"],
                "verbose_name_plural": "Conversat Groups",
            },
        ),
        migrations.AlterField(
            model_name="group",
            name="group_pic",
            field=models.FileField(
                blank=True,
                default="group_pic/default_group_pic.jpg",
                max_length=355,
                null=True,
                upload_to="group_pic/",
            ),
        ),
    ]
