# Generated by Django 4.2.3 on 2023-07-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_remove_group_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
