# Generated by Django 4.2.3 on 2023-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_alter_chatmessages_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessages",
            name="file_name",
            field=models.CharField(blank=True, max_length=655, null=True),
        ),
    ]
