# Generated by Django 4.2.3 on 2023-07-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_chatmessages_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessages",
            name="file_ext",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatmessages",
            name="file_size",
            field=models.CharField(default="0", max_length=255),
        ),
    ]
