# Generated by Django 4.2.3 on 2023-07-31 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0017_chatmessages_file_ext_chatmessages_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="online",
            field=models.ManyToManyField(
                related_name="online", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
