# Generated by Django 4.2.3 on 2023-07-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0018_group_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessages",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
