# Generated by Django 4.2.3 on 2023-07-15 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usercontacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontacts",
            name="contacts",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
