# Generated by Django 4.2.3 on 2023-07-20 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_usercontacts_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontacts",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
