# Generated by Django 4.2.3 on 2023-07-23 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_usercontacts_contacts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["date_joined"],
                "verbose_name_plural": "Conversat User",
            },
        ),
    ]
