# Generated by Django 4.2.3 on 2023-07-31 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=655)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("personal", "personal"),
                            ("group", "Group"),
                            ("application", "Application"),
                        ],
                        max_length=255,
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                (
                    "notification_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
