# Generated by Django 4.2.3 on 2023-07-31 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_friendrequests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friendrequests",
            options={"verbose_name_plural": "Friend Request"},
        ),
    ]
