# Generated by Django 4.2.3 on 2023-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_friendrequests_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequests",
            name="message",
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
