# Generated by Django 4.2.3 on 2023-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_friendrequests_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequests",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
