# Generated by Django 4.2.3 on 2023-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_remove_friendrequests_message_notification_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=655),
        ),
    ]
